# ----------------------- #
#      Main Configs       #
# ----------------------- #
title: 慎独
subtitle: 诚其意者，毋自欺也.
author: Shawhu
subscribe_rss: /atom.xml
license: true
category_list: true
tag_cloud: true
links: true

# ----------------------- #
#    Jekyll Config        #
# ----------------------- #
root: /
permalink: /blog/:year/:month/:day/:title/
#source: source
#destination: public
plugins: plugins
markdown: rdiscount
pygments: true 
paginate: 5           # Posts per page on the blog index
pagination_dir: blog
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"
titlecase: true

# ----------------------- #
#    Javascript Plugins   #
# ----------------------- #
disqus_short_name: shawhu
disqus_show_comment_count: 5
google_analytics_tracking_id: UA-34850864-1
google_search_id: 010105547632735252772:zhur5xgjxg8

#Generate css
#compass compile

